subreddit: #limit to 4 b/c there are 4 cores on raspberry pi for spark to share
  - AsiansGoneWild
  - GoneWild18
  - transgonewild
  - asstastic
  - latinas
  - IndiansGoneWild
  - GoneWild
  - traps
post_type: new
kafka_host: kafka #kafka
spark_host: spark-master #spark-master
debug: True
