.nh
.TH "GH-API" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-api - Make an authenticated GitHub API request


.SH SYNOPSIS
.PP
\fB\fCgh api <endpoint> [flags]\fR


.SH DESCRIPTION
.PP
Makes an authenticated HTTP request to the GitHub API and prints the response.

.PP
The endpoint argument should either be a path of a GitHub API v3 endpoint, or
"graphql" to access the GitHub API v4.

.PP
Placeholder values "{owner}", "{repo}", and "{branch}" in the endpoint
argument will get replaced with values from the repository of the current
directory or the repository specified in the GH_REPO environment variable.
Note that in some shells, for example PowerShell, you may need to enclose
any value that contains "{...}" in quotes to prevent the shell from
applying special meaning to curly braces.

.PP
The default HTTP request method is "GET" normally and "POST" if any parameters
were added. Override the method with \fB\fC--method\fR\&.

.PP
Pass one or more \fB\fC-f/--raw-field\fR values in "key=value" format to add static string
parameters to the request payload. To add non-string or otherwise dynamic values, see
\fB\fC--field\fR below. Note that adding request parameters will automatically switch the
request method to POST. To send the parameters as a GET query string instead, use
\fB\fC--method GET\fR\&.

.PP
The \fB\fC-F/--field\fR flag has magic type conversion based on the format of the value:

.RS
.IP \(bu 2
literal values "true", "false", "null", and integer numbers get converted to
appropriate JSON types;
.IP \(bu 2
placeholder values "{owner}", "{repo}", and "{branch}" get populated with values
from the repository of the current directory;
.IP \(bu 2
if the value starts with "@", the rest of the value is interpreted as a
filename to read the value from. Pass "-" to read from standard input.

.RE

.PP
For GraphQL requests, all fields other than "query" and "operationName" are
interpreted as GraphQL variables.

.PP
Raw request body may be passed from the outside via a file specified by \fB\fC--input\fR\&.
Pass "-" to read from standard input. In this mode, parameters specified via
\fB\fC--field\fR flags are serialized into URL query parameters.

.PP
In \fB\fC--paginate\fR mode, all pages of results will sequentially be requested until
there are no more pages of results. For GraphQL requests, this requires that the
original query accepts an \fB\fC$endCursor: String\fR variable and that it fetches the
\fB\fCpageInfo{ hasNextPage, endCursor }\fR set of fields from a collection.


.SH OPTIONS
.TP
\fB\fC--cache\fR \fB\fC<duration>\fR
Cache the response, e.g. "3600s", "60m", "1h"

.TP
\fB\fC-F\fR, \fB\fC--field\fR \fB\fC<key=value>\fR
Add a typed parameter in key=value format

.TP
\fB\fC-H\fR, \fB\fC--header\fR \fB\fC<key:value>\fR
Add a HTTP request header in key:value format

.TP
\fB\fC--hostname\fR \fB\fC<string>\fR
The GitHub hostname for the request (default "github.com")

.TP
\fB\fC-i\fR, \fB\fC--include\fR
Include HTTP response status line and headers in the output

.TP
\fB\fC--input\fR \fB\fC<file>\fR
The file to use as body for the HTTP request (use "-" to read from standard input)

.TP
\fB\fC-q\fR, \fB\fC--jq\fR \fB\fC<string>\fR
Query to select values from the response using jq syntax

.TP
\fB\fC-X\fR, \fB\fC--method\fR \fB\fC<string>\fR
The HTTP method for the request

.TP
\fB\fC--paginate\fR
Make additional HTTP requests to fetch all pages of results

.TP
\fB\fC-p\fR, \fB\fC--preview\fR \fB\fC<names>\fR
GitHub API preview names to request (without the "-preview" suffix)

.TP
\fB\fC-f\fR, \fB\fC--raw-field\fR \fB\fC<key=value>\fR
Add a string parameter in key=value format

.TP
\fB\fC--silent\fR
Do not print the response body

.TP
\fB\fC-t\fR, \fB\fC--template\fR \fB\fC<string>\fR
Format the response using a Go template


.SH EXAMPLE
.PP
.RS

.nf
# list releases in the current repository
$ gh api repos/{owner}/{repo}/releases

# post an issue comment
$ gh api repos/{owner}/{repo}/issues/123/comments -f body='Hi from CLI'

# add parameters to a GET request
$ gh api -X GET search/issues -f q='repo:cli/cli is:open remote'

# set a custom HTTP header
$ gh api -H 'Accept: application/vnd.github.v3.raw+json' ...

# opt into GitHub API previews
$ gh api --preview baptiste,nebula ...

# print only specific fields from the response
$ gh api repos/{owner}/{repo}/issues --jq '.[].title'

# use a template for the output
$ gh api repos/{owner}/{repo}/issues --template \\
  '{{range .}}{{.title}} ({{.labels | pluck "name" | join ", " | color "yellow"}}){{"\\n"}}{{end}}'

# list releases with GraphQL
$ gh api graphql -F owner='{owner}' -F name='{repo}' -f query='
  query($name: String!, $owner: String!) {
    repository(owner: $owner, name: $name) {
      releases(last: 3) {
        nodes { tagName }
      }
    }
  }
'

# list all repositories for a user
$ gh api graphql --paginate -f query='
  query($endCursor: String) {
    viewer {
      repositories(first: 100, after: $endCursor) {
        nodes { nameWithOwner }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
'


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh(1)\fR
