.nh
.TH "GH-AUTH" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-auth - Authenticate gh and git with GitHub


.SH SYNOPSIS
.PP
\fB\fCgh auth <command> [flags]\fR


.SH COMMANDS
.TP
\fB\fCgh-auth-login(1)\fR
Authenticate with a GitHub host

.TP
\fB\fCgh-auth-logout(1)\fR
Log out of a GitHub host

.TP
\fB\fCgh-auth-refresh(1)\fR
Refresh stored authentication credentials

.TP
\fB\fCgh-auth-setup-git(1)\fR
Configure git to use GitHub CLI as a credential helper

.TP
\fB\fCgh-auth-status(1)\fR
View authentication status


.SH SEE ALSO
.PP
\fB\fCgh(1)\fR
