.nh
.TH "GH-ALIAS" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-alias - Create command shortcuts


.SH SYNOPSIS
.PP
\fB\fCgh alias <command> [flags]\fR


.SH DESCRIPTION
.PP
Aliases can be used to make shortcuts for gh commands or to compose multiple commands.

.PP
Run "gh help alias set" to learn more.


.SH COMMANDS
.TP
\fB\fCgh-alias-delete(1)\fR
Delete an alias

.TP
\fB\fCgh-alias-list(1)\fR
List your aliases

.TP
\fB\fCgh-alias-set(1)\fR
Create a shortcut for a gh command


.SH SEE ALSO
.PP
\fB\fCgh(1)\fR
