.nh
.TH "GH-AUTH-STATUS" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-auth-status - View authentication status


.SH SYNOPSIS
.PP
\fB\fCgh auth status [flags]\fR


.SH DESCRIPTION
.PP
Verifies and displays information about your authentication state.

.PP
This command will test your authentication state for each GitHub host that gh knows about and
report on any issues.


.SH OPTIONS
.TP
\fB\fC-h\fR, \fB\fC--hostname\fR \fB\fC<string>\fR
Check a specific hostname's auth status

.TP
\fB\fC-t\fR, \fB\fC--show-token\fR
Display the auth token


.SH SEE ALSO
.PP
\fB\fCgh-auth(1)\fR
