.nh
.TH "GH-AUTH-SETUP-GIT" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-auth-setup-git - Configure git to use GitHub CLI as a credential helper


.SH SYNOPSIS
.PP
\fB\fCgh auth setup-git [flags]\fR


.SH OPTIONS
.TP
\fB\fC-h\fR, \fB\fC--hostname\fR \fB\fC<string>\fR
The hostname to configure git for


.SH SEE ALSO
.PP
\fB\fCgh-auth(1)\fR
