.nh
.TH "GH-ALIAS-LIST" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-alias-list - List your aliases


.SH SYNOPSIS
.PP
\fB\fCgh alias list [flags]\fR


.SH DESCRIPTION
.PP
This command prints out all of the aliases gh is configured to use.


.SH SEE ALSO
.PP
\fB\fCgh-alias(1)\fR
