.nh
.TH "GH-CODESPACE-PORTS-FORWARD" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-ports-forward - Forward ports


.SH SYNOPSIS
.PP
\fB\fCgh codespace ports forward <remote-port>:<local-port>... [flags]\fR


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-c\fR, \fB\fC--codespace\fR \fB\fC<string>\fR
Name of the codespace


.SH SEE ALSO
.PP
\fB\fCgh-codespace-ports(1)\fR
