.nh
.TH "GH-CODESPACE-JUPYTER" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-jupyter - Open a codespace in JupyterLab


.SH SYNOPSIS
.PP
\fB\fCgh codespace jupyter [flags]\fR


.SH OPTIONS
.TP
\fB\fC-c\fR, \fB\fC--codespace\fR \fB\fC<string>\fR
Name of the codespace


.SH SEE ALSO
.PP
\fB\fCgh-codespace(1)\fR
