.nh
.TH "GH-CODESPACE" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace - Connect to and manage codespaces


.SH SYNOPSIS
.PP
\fB\fCgh codespace [flags]\fR


.SH COMMANDS
.TP
\fB\fCgh-codespace-code(1)\fR
Open a codespace in Visual Studio Code

.TP
\fB\fCgh-codespace-cp(1)\fR
Copy files between local and remote file systems

.TP
\fB\fCgh-codespace-create(1)\fR
Create a codespace

.TP
\fB\fCgh-codespace-delete(1)\fR
Delete codespaces

.TP
\fB\fCgh-codespace-edit(1)\fR
Edit a codespace

.TP
\fB\fCgh-codespace-jupyter(1)\fR
Open a codespace in JupyterLab

.TP
\fB\fCgh-codespace-list(1)\fR
List codespaces

.TP
\fB\fCgh-codespace-logs(1)\fR
Access codespace logs

.TP
\fB\fCgh-codespace-ports(1)\fR
List ports in a codespace

.TP
\fB\fCgh-codespace-ssh(1)\fR
SSH into a codespace

.TP
\fB\fCgh-codespace-stop(1)\fR
Stop a running codespace


.SH SEE ALSO
.PP
\fB\fCgh(1)\fR
