.nh
.TH "GH-CODESPACE-PORTS" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-ports - List ports in a codespace


.SH SYNOPSIS
.PP
\fB\fCgh codespace ports [flags]\fR


.SH COMMANDS
.TP
\fB\fCgh-codespace-ports-forward(1)\fR
Forward ports

.TP
\fB\fCgh-codespace-ports-visibility(1)\fR
Change the visibility of the forwarded port


.SH OPTIONS
.TP
\fB\fC-c\fR, \fB\fC--codespace\fR \fB\fC<string>\fR
Name of the codespace

.TP
\fB\fC-q\fR, \fB\fC--jq\fR \fB\fC<expression>\fR
Filter JSON output using a jq expression

.TP
\fB\fC--json\fR \fB\fC<fields>\fR
Output JSON with the specified fields

.TP
\fB\fC-t\fR, \fB\fC--template\fR \fB\fC<string>\fR
Format JSON output using a Go template


.SH SEE ALSO
.PP
\fB\fCgh-codespace(1)\fR
