.nh
.TH "GH-CODESPACE-LIST" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-list - List codespaces


.SH SYNOPSIS
.PP
\fB\fCgh codespace list [flags]\fR


.SH DESCRIPTION
.PP
List codespaces of the authenticated user.

.PP
Alternatively, organization administrators may list all codespaces billed to the organization.


.SH OPTIONS
.TP
\fB\fC-q\fR, \fB\fC--jq\fR \fB\fC<expression>\fR
Filter JSON output using a jq expression

.TP
\fB\fC--json\fR \fB\fC<fields>\fR
Output JSON with the specified fields

.TP
\fB\fC-L\fR, \fB\fC--limit\fR \fB\fC<int>\fR
Maximum number of codespaces to list

.TP
\fB\fC-o\fR, \fB\fC--org\fR \fB\fC<login>\fR
The login handle of the organization to list codespaces for (admin-only)

.TP
\fB\fC-t\fR, \fB\fC--template\fR \fB\fC<string>\fR
Format JSON output using a Go template

.TP
\fB\fC-u\fR, \fB\fC--user\fR \fB\fC<username>\fR
The username to list codespaces for (used with --org)


.SH SEE ALSO
.PP
\fB\fCgh-codespace(1)\fR
