.nh
.TH "GH-CODESPACE-DELETE" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-delete - Delete codespaces


.SH SYNOPSIS
.PP
\fB\fCgh codespace delete [flags]\fR


.SH DESCRIPTION
.PP
Delete codespaces based on selection criteria.

.PP
All codespaces for the authenticated user can be deleted, as well as codespaces for a
specific repository. Alternatively, only codespaces older than N days can be deleted.

.PP
Organization administrators may delete any codespace billed to the organization.


.SH OPTIONS
.TP
\fB\fC--all\fR
Delete all codespaces

.TP
\fB\fC-c\fR, \fB\fC--codespace\fR \fB\fC<string>\fR
Name of the codespace

.TP
\fB\fC--days\fR \fB\fC<N>\fR
Delete codespaces older than N days

.TP
\fB\fC-f\fR, \fB\fC--force\fR
Skip confirmation for codespaces that contain unsaved changes

.TP
\fB\fC-o\fR, \fB\fC--org\fR \fB\fC<login>\fR
The login handle of the organization (admin-only)

.TP
\fB\fC-r\fR, \fB\fC--repo\fR \fB\fC<repository>\fR
Delete codespaces for a repository

.TP
\fB\fC-u\fR, \fB\fC--user\fR \fB\fC<username>\fR
The username to delete codespaces for (used with --org)


.SH SEE ALSO
.PP
\fB\fCgh-codespace(1)\fR
