.nh
.TH "GH-CODESPACE-LOGS" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-logs - Access codespace logs


.SH SYNOPSIS
.PP
\fB\fCgh codespace logs [flags]\fR


.SH OPTIONS
.TP
\fB\fC-c\fR, \fB\fC--codespace\fR \fB\fC<string>\fR
Name of the codespace

.TP
\fB\fC-f\fR, \fB\fC--follow\fR
Tail and follow the logs


.SH SEE ALSO
.PP
\fB\fCgh-codespace(1)\fR
