.nh
.TH "GH-CODESPACE-CODE" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-code - Open a codespace in Visual Studio Code


.SH SYNOPSIS
.PP
\fB\fCgh codespace code [flags]\fR


.SH OPTIONS
.TP
\fB\fC-c\fR, \fB\fC--codespace\fR \fB\fC<string>\fR
Name of the codespace

.TP
\fB\fC--insiders\fR
Use the insiders version of Visual Studio Code

.TP
\fB\fC-w\fR, \fB\fC--web\fR
Use the web version of Visual Studio Code


.SH SEE ALSO
.PP
\fB\fCgh-codespace(1)\fR
