.nh
.TH "GH-CODESPACE-EDIT" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-edit - Edit a codespace


.SH SYNOPSIS
.PP
\fB\fCgh codespace edit [flags]\fR


.SH OPTIONS
.TP
\fB\fC-c\fR, \fB\fC--codespace\fR \fB\fC<string>\fR
Name of the codespace

.TP
\fB\fC-d\fR, \fB\fC--display-name\fR \fB\fC<string>\fR
Set the display name

.TP
\fB\fC-m\fR, \fB\fC--machine\fR \fB\fC<string>\fR
Set hardware specifications for the VM


.SH SEE ALSO
.PP
\fB\fCgh-codespace(1)\fR
