.nh
.TH "GH-CODESPACE-PORTS-VISIBILITY" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-ports-visibility - Change the visibility of the forwarded port


.SH SYNOPSIS
.PP
\fB\fCgh codespace ports visibility <port>:{public|private|org}... [flags]\fR


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-c\fR, \fB\fC--codespace\fR \fB\fC<string>\fR
Name of the codespace


.SH EXAMPLE
.PP
.RS

.nf
gh codespace ports visibility 80:org 3000:private 8000:public

.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-codespace-ports(1)\fR
