.nh
.TH "GH-EXTENSION-EXEC" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-extension-exec - Execute an installed extension


.SH SYNOPSIS
.PP
\fB\fCgh extension exec <name> [args] [flags]\fR


.SH DESCRIPTION
.PP
Execute an extension using the short name. For example, if the extension repository is
"owner/gh-extension", you should pass "extension". You can use this command when
the short name conflicts with a core gh command.

.PP
All arguments after the extension name will be forwarded to the executable
of the extension.


.SH EXAMPLE
.PP
.RS

.nf
# execute a label extension instead of the core gh label command
$ gh extension exec label


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-extension(1)\fR
