.nh
.TH "GH-EXTENSION-INSTALL" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-extension-install - Install a gh extension from a repository


.SH SYNOPSIS
.PP
\fB\fCgh extension install <repository> [flags]\fR


.SH DESCRIPTION
.PP
Install a GitHub repository locally as a GitHub CLI extension.

.PP
The repository argument can be specified in "owner/repo" format as well as a full URL.
The URL format is useful when the repository is not hosted on github.com.

.PP
To install an extension in development from the current directory, use "." as the
value of the repository argument.

.PP
See the list of available extensions at https://github.com/topics/gh-extension
\[la]https://github.com/topics/gh-extension\[ra]\&.


.SH OPTIONS
.TP
\fB\fC--pin\fR \fB\fC<string>\fR
pin extension to a release tag or commit ref


.SH EXAMPLE
.PP
.RS

.nf
$ gh extension install owner/gh-extension
$ gh extension install https://git.example.com/owner/gh-extension
$ gh extension install .


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-extension(1)\fR
