.nh
.TH "GH-GPG-KEY" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-gpg-key - Manage GPG keys


.SH SYNOPSIS
.PP
\fB\fCgh gpg-key <command> [flags]\fR


.SH DESCRIPTION
.PP
Manage GPG keys registered with your GitHub account.


.SH COMMANDS
.TP
\fB\fCgh-gpg-key-add(1)\fR
Add a GPG key to your GitHub account

.TP
\fB\fCgh-gpg-key-list(1)\fR
Lists GPG keys in your GitHub account


.SH SEE ALSO
.PP
\fB\fCgh(1)\fR
