.nh
.TH "GH-GIST" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-gist - Manage gists


.SH SYNOPSIS
.PP
\fB\fCgh gist <command> [flags]\fR


.SH DESCRIPTION
.PP
Work with GitHub gists.


.SH COMMANDS
.TP
\fB\fCgh-gist-clone(1)\fR
Clone a gist locally

.TP
\fB\fCgh-gist-create(1)\fR
Create a new gist

.TP
\fB\fCgh-gist-delete(1)\fR
Delete a gist

.TP
\fB\fCgh-gist-edit(1)\fR
Edit one of your gists

.TP
\fB\fCgh-gist-list(1)\fR
List your gists

.TP
\fB\fCgh-gist-view(1)\fR
View a gist


.SH SEE ALSO
.PP
\fB\fCgh(1)\fR
