.nh
.TH "GH-GIST-LIST" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-gist-list - List your gists


.SH SYNOPSIS
.PP
\fB\fCgh gist list [flags]\fR


.SH OPTIONS
.TP
\fB\fC-L\fR, \fB\fC--limit\fR \fB\fC<int>\fR
Maximum number of gists to fetch

.TP
\fB\fC--public\fR
Show only public gists

.TP
\fB\fC--secret\fR
Show only secret gists


.SH SEE ALSO
.PP
\fB\fCgh-gist(1)\fR
