.nh
.TH "GH-ISSUE-CLOSE" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-issue-close - Close issue


.SH SYNOPSIS
.PP
\fB\fCgh issue close {<number> | <url>} [flags]\fR


.SH OPTIONS
.TP
\fB\fC-c\fR, \fB\fC--comment\fR \fB\fC<string>\fR
Leave a closing comment


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-issue(1)\fR
