.nh
.TH "GH-ISSUE" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-issue - Manage issues


.SH SYNOPSIS
.PP
\fB\fCgh issue <command> [flags]\fR


.SH DESCRIPTION
.PP
Work with GitHub issues.


.SH COMMANDS
.TP
\fB\fCgh-issue-close(1)\fR
Close issue

.TP
\fB\fCgh-issue-comment(1)\fR
Add a comment to an issue

.TP
\fB\fCgh-issue-create(1)\fR
Create a new issue

.TP
\fB\fCgh-issue-delete(1)\fR
Delete issue

.TP
\fB\fCgh-issue-edit(1)\fR
Edit an issue

.TP
\fB\fCgh-issue-list(1)\fR
List issues in a repository

.TP
\fB\fCgh-issue-reopen(1)\fR
Reopen issue

.TP
\fB\fCgh-issue-status(1)\fR
Show status of relevant issues

.TP
\fB\fCgh-issue-transfer(1)\fR
Transfer issue to another repository

.TP
\fB\fCgh-issue-view(1)\fR
View an issue


.SH OPTIONS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXAMPLE
.PP
.RS

.nf
$ gh issue list
$ gh issue create --label bug
$ gh issue view 123 --web


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh(1)\fR
