.nh
.TH "GH-ISSUE-TRANSFER" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-issue-transfer - Transfer issue to another repository


.SH SYNOPSIS
.PP
\fB\fCgh issue transfer {<number> | <url>} <destination-repo> [flags]\fR


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-issue(1)\fR
