.nh
.TH "GH-LABEL-DELETE" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-label-delete - Delete a label from a repository


.SH SYNOPSIS
.PP
\fB\fCgh label delete <name> [flags]\fR


.SH OPTIONS
.TP
\fB\fC--confirm\fR
Confirm deletion without prompting


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-label(1)\fR
