.nh
.TH "GH-LABEL-EDIT" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-label-edit - Edit a label


.SH SYNOPSIS
.PP
\fB\fCgh label edit <name> [flags]\fR


.SH DESCRIPTION
.PP
Update a label on GitHub.

.PP
A label can be renamed using the \fB\fC--name\fR flag.

.PP
The label color needs to be 6 character hex value.


.SH OPTIONS
.TP
\fB\fC-c\fR, \fB\fC--color\fR \fB\fC<string>\fR
Color of the label

.TP
\fB\fC-d\fR, \fB\fC--description\fR \fB\fC<string>\fR
Description of the label

.TP
\fB\fC-n\fR, \fB\fC--name\fR \fB\fC<string>\fR
New name of the label


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXAMPLE
.PP
.RS

.nf
# update the color of the bug label
$ gh label edit bug --color FF0000

# rename and edit the description of the bug label
$ gh label edit bug --name big-bug --description "Bigger than normal bug"


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-label(1)\fR
