.nh
.TH "GH-LABEL" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-label - Manage labels


.SH SYNOPSIS
.PP
\fB\fCgh label <command> [flags]\fR


.SH DESCRIPTION
.PP
Work with GitHub labels.


.SH COMMANDS
.TP
\fB\fCgh-label-clone(1)\fR
Clones labels from one repository to another

.TP
\fB\fCgh-label-create(1)\fR
Create a new label

.TP
\fB\fCgh-label-delete(1)\fR
Delete a label from a repository

.TP
\fB\fCgh-label-edit(1)\fR
Edit a label

.TP
\fB\fCgh-label-list(1)\fR
List labels in a repository


.SH OPTIONS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh(1)\fR
