.nh
.TH "GH-PR-REVIEW" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-pr-review - Add a review to a pull request


.SH SYNOPSIS
.PP
\fB\fCgh pr review [<number> | <url> | <branch>] [flags]\fR


.SH DESCRIPTION
.PP
Add a review to a pull request.

.PP
Without an argument, the pull request that belongs to the current branch is reviewed.


.SH OPTIONS
.TP
\fB\fC-a\fR, \fB\fC--approve\fR
Approve pull request

.TP
\fB\fC-b\fR, \fB\fC--body\fR \fB\fC<string>\fR
Specify the body of a review

.TP
\fB\fC-F\fR, \fB\fC--body-file\fR \fB\fC<file>\fR
Read body text from file (use "-" to read from standard input)

.TP
\fB\fC-c\fR, \fB\fC--comment\fR
Comment on a pull request

.TP
\fB\fC-r\fR, \fB\fC--request-changes\fR
Request changes on a pull request


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXAMPLE
.PP
.RS

.nf
# approve the pull request of the current branch
$ gh pr review --approve

# leave a review comment for the current branch
$ gh pr review --comment -b "interesting"

# add a review for a specific pull request
$ gh pr review 123

# request changes on a specific pull request
$ gh pr review 123 -r -b "needs more ASCII art"


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-pr(1)\fR
