.nh
.TH "GH-PR-CHECKOUT" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-pr-checkout - Check out a pull request in git


.SH SYNOPSIS
.PP
\fB\fCgh pr checkout {<number> | <url> | <branch>} [flags]\fR


.SH OPTIONS
.TP
\fB\fC-b\fR, \fB\fC--branch\fR \fB\fC<string>\fR
Local branch name to use (default: the name of the head branch)

.TP
\fB\fC--detach\fR
Checkout PR with a detached HEAD

.TP
\fB\fC-f\fR, \fB\fC--force\fR
Reset the existing local branch to the latest state of the pull request

.TP
\fB\fC--recurse-submodules\fR
Update all submodules after checkout


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-pr(1)\fR
