.nh
.TH "GH-PR-READY" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-pr-ready - Mark a pull request as ready for review


.SH SYNOPSIS
.PP
\fB\fCgh pr ready [<number> | <url> | <branch>] [flags]\fR


.SH DESCRIPTION
.PP
Mark a pull request as ready for review.

.PP
Without an argument, the pull request that belongs to the current branch
is marked as ready.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-pr(1)\fR
