.nh
.TH "GH-PR-LIST" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-pr-list - List pull requests in a repository


.SH SYNOPSIS
.PP
\fB\fCgh pr list [flags]\fR


.SH DESCRIPTION
.PP
List pull requests in a GitHub repository.

.PP
The search query syntax is documented here:
https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests
\[la]https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests\[ra]


.SH OPTIONS
.TP
\fB\fC--app\fR \fB\fC<string>\fR
Filter by GitHub App author

.TP
\fB\fC-a\fR, \fB\fC--assignee\fR \fB\fC<string>\fR
Filter by assignee

.TP
\fB\fC-A\fR, \fB\fC--author\fR \fB\fC<string>\fR
Filter by author

.TP
\fB\fC-B\fR, \fB\fC--base\fR \fB\fC<string>\fR
Filter by base branch

.TP
\fB\fC-d\fR, \fB\fC--draft\fR
Filter by draft state

.TP
\fB\fC-H\fR, \fB\fC--head\fR \fB\fC<string>\fR
Filter by head branch

.TP
\fB\fC-q\fR, \fB\fC--jq\fR \fB\fC<expression>\fR
Filter JSON output using a jq expression

.TP
\fB\fC--json\fR \fB\fC<fields>\fR
Output JSON with the specified fields

.TP
\fB\fC-l\fR, \fB\fC--label\fR \fB\fC<strings>\fR
Filter by label

.TP
\fB\fC-L\fR, \fB\fC--limit\fR \fB\fC<int>\fR
Maximum number of items to fetch

.TP
\fB\fC-S\fR, \fB\fC--search\fR \fB\fC<query>\fR
Search pull requests with query

.TP
\fB\fC-s\fR, \fB\fC--state\fR \fB\fC<string>\fR
Filter by state: {open|closed|merged|all}

.TP
\fB\fC-t\fR, \fB\fC--template\fR \fB\fC<string>\fR
Format JSON output using a Go template

.TP
\fB\fC-w\fR, \fB\fC--web\fR
List pull requests in the web browser


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXAMPLE
.PP
.RS

.nf
List PRs authored by you
$ gh pr list --author "@me"

List only PRs with all of the given labels
$ gh pr list --label bug --label "priority 1"

Filter PRs using search syntax
$ gh pr list --search "status:success review:required"

Find a PR that introduced a given commit
$ gh pr list --search "<SHA>" --state merged
 	

.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-pr(1)\fR
