.nh
.TH "GH-PR-VIEW" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-pr-view - View a pull request


.SH SYNOPSIS
.PP
\fB\fCgh pr view [<number> | <url> | <branch>] [flags]\fR


.SH DESCRIPTION
.PP
Display the title, body, and other information about a pull request.

.PP
Without an argument, the pull request that belongs to the current branch
is displayed.

.PP
With '--web', open the pull request in a web browser instead.


.SH OPTIONS
.TP
\fB\fC-c\fR, \fB\fC--comments\fR
View pull request comments

.TP
\fB\fC-q\fR, \fB\fC--jq\fR \fB\fC<expression>\fR
Filter JSON output using a jq expression

.TP
\fB\fC--json\fR \fB\fC<fields>\fR
Output JSON with the specified fields

.TP
\fB\fC-t\fR, \fB\fC--template\fR \fB\fC<string>\fR
Format JSON output using a Go template

.TP
\fB\fC-w\fR, \fB\fC--web\fR
Open a pull request in the browser


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-pr(1)\fR
