.nh
.TH "GH-RUN-CANCEL" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-run-cancel - Cancel a workflow run


.SH SYNOPSIS
.PP
\fB\fCgh run cancel [<run-id>] [flags]\fR


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-run(1)\fR
