.nh
.TH "GH-REPO-ARCHIVE" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-repo-archive - Archive a repository


.SH SYNOPSIS
.PP
\fB\fCgh repo archive [<repository>] [flags]\fR


.SH DESCRIPTION
.PP
Archive a GitHub repository.

.PP
With no argument, archives the current repository.


.SH OPTIONS
.TP
\fB\fC-y\fR, \fB\fC--confirm\fR
Skip the confirmation prompt


.SH SEE ALSO
.PP
\fB\fCgh-repo(1)\fR
