.nh
.TH "GH-REPO" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-repo - Manage repositories


.SH SYNOPSIS
.PP
\fB\fCgh repo <command> [flags]\fR


.SH DESCRIPTION
.PP
Work with GitHub repositories.


.SH COMMANDS
.TP
\fB\fCgh-repo-archive(1)\fR
Archive a repository

.TP
\fB\fCgh-repo-clone(1)\fR
Clone a repository locally

.TP
\fB\fCgh-repo-create(1)\fR
Create a new repository

.TP
\fB\fCgh-repo-delete(1)\fR
Delete a repository

.TP
\fB\fCgh-repo-deploy-key(1)\fR
Manage deploy keys in a repository

.TP
\fB\fCgh-repo-edit(1)\fR
Edit repository settings

.TP
\fB\fCgh-repo-fork(1)\fR
Create a fork of a repository

.TP
\fB\fCgh-repo-list(1)\fR
List repositories owned by user or organization

.TP
\fB\fCgh-repo-rename(1)\fR
Rename a repository

.TP
\fB\fCgh-repo-sync(1)\fR
Sync a repository

.TP
\fB\fCgh-repo-view(1)\fR
View a repository


.SH EXAMPLE
.PP
.RS

.nf
$ gh repo create
$ gh repo clone cli/cli
$ gh repo view --web


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh(1)\fR
