.nh
.TH "GH-RELEASE-LIST" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-release-list - List releases in a repository


.SH SYNOPSIS
.PP
\fB\fCgh release list [flags]\fR


.SH OPTIONS
.TP
\fB\fC--exclude-drafts\fR
Exclude draft releases

.TP
\fB\fC-L\fR, \fB\fC--limit\fR \fB\fC<int>\fR
Maximum number of items to fetch


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-release(1)\fR
