.nh
.TH "GH-RELEASE-DELETE" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-release-delete - Delete a release


.SH SYNOPSIS
.PP
\fB\fCgh release delete <tag> [flags]\fR


.SH OPTIONS
.TP
\fB\fC-y\fR, \fB\fC--yes\fR
Skip the confirmation prompt


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-release(1)\fR
