.nh
.TH "GH-REPO-RENAME" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-repo-rename - Rename a repository


.SH SYNOPSIS
.PP
\fB\fCgh repo rename [<new-name>] [flags]\fR


.SH DESCRIPTION
.PP
Rename a GitHub repository.

.PP
By default, this renames the current repository; otherwise renames the specified repository.


.SH OPTIONS
.TP
\fB\fC-y\fR, \fB\fC--confirm\fR
skip confirmation prompt

.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-repo(1)\fR
