.nh
.TH "GH-REPO-VIEW" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-repo-view - View a repository


.SH SYNOPSIS
.PP
\fB\fCgh repo view [<repository>] [flags]\fR


.SH DESCRIPTION
.PP
Display the description and the README of a GitHub repository.

.PP
With no argument, the repository for the current directory is displayed.

.PP
With '--web', open the repository in a web browser instead.

.PP
With '--branch', view a specific branch of the repository.


.SH OPTIONS
.TP
\fB\fC-b\fR, \fB\fC--branch\fR \fB\fC<string>\fR
View a specific branch of the repository

.TP
\fB\fC-q\fR, \fB\fC--jq\fR \fB\fC<expression>\fR
Filter JSON output using a jq expression

.TP
\fB\fC--json\fR \fB\fC<fields>\fR
Output JSON with the specified fields

.TP
\fB\fC-t\fR, \fB\fC--template\fR \fB\fC<string>\fR
Format JSON output using a Go template

.TP
\fB\fC-w\fR, \fB\fC--web\fR
Open a repository in the browser


.SH SEE ALSO
.PP
\fB\fCgh-repo(1)\fR
