.nh
.TH "GH-REPO-CLONE" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-repo-clone - Clone a repository locally


.SH SYNOPSIS
.PP
\fB\fCgh repo clone <repository> [<directory>] [-- <gitflags>...]\fR


.SH DESCRIPTION
.PP
Clone a GitHub repository locally. Pass additional \fB\fCgit clone\fR flags by listing
them after "--".

.PP
If the "OWNER/" portion of the "OWNER/REPO" repository argument is omitted, it
defaults to the name of the authenticating user.

.PP
If the repository is a fork, its parent repository will be added as an additional
git remote called "upstream". The remote name can be configured using \fB\fC--upstream-remote-name\fR\&.
The \fB\fC--upstream-remote-name\fR option supports an "@owner" value which will name
the remote after the owner of the parent repository.


.SH OPTIONS
.TP
\fB\fC-u\fR, \fB\fC--upstream-remote-name\fR \fB\fC<string>\fR
Upstream remote name when cloning a fork


.SH SEE ALSO
.PP
\fB\fCgh-repo(1)\fR
