.nh
.TH "GH-RELEASE-EDIT" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-release-edit - Edit a release


.SH SYNOPSIS
.PP
\fB\fCgh release edit <tag>\fR


.SH OPTIONS
.TP
\fB\fC--discussion-category\fR \fB\fC<string>\fR
Start a discussion in the specified category when publishing a draft

.TP
\fB\fC--draft\fR
Save the release as a draft instead of publishing it

.TP
\fB\fC-n\fR, \fB\fC--notes\fR \fB\fC<string>\fR
Release notes

.TP
\fB\fC-F\fR, \fB\fC--notes-file\fR \fB\fC<file>\fR
Read release notes from file (use "-" to read from standard input)

.TP
\fB\fC--prerelease\fR
Mark the release as a prerelease

.TP
\fB\fC--tag\fR \fB\fC<string>\fR
The name of the tag

.TP
\fB\fC--target\fR \fB\fC<branch>\fR
Target branch or full commit SHA (default: main branch)

.TP
\fB\fC-t\fR, \fB\fC--title\fR \fB\fC<string>\fR
Release title


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXAMPLE
.PP
.RS

.nf
Publish a release that was previously a draft
$ gh release edit v1.0 --draft=false

Update the release notes from the content of a file
$ gh release edit v1.0 --notes-file /path/to/release_notes.md


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-release(1)\fR
