.nh
.TH "GH-REPO-DEPLOY-KEY" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-repo-deploy-key - Manage deploy keys in a repository


.SH SYNOPSIS
.PP
\fB\fCgh repo deploy-key <command> [flags]\fR


.SH COMMANDS
.TP
\fB\fCgh-repo-deploy-key-add(1)\fR
Add a deploy key to a GitHub repository

.TP
\fB\fCgh-repo-deploy-key-delete(1)\fR
Delete a deploy key from a GitHub repository

.TP
\fB\fCgh-repo-deploy-key-list(1)\fR
List deploy keys in a GitHub repository


.SH OPTIONS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-repo(1)\fR
