.nh
.TH "GH-REPO-LIST" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-repo-list - List repositories owned by user or organization


.SH SYNOPSIS
.PP
\fB\fCgh repo list [<owner>] [flags]\fR


.SH OPTIONS
.TP
\fB\fC--archived\fR
Show only archived repositories

.TP
\fB\fC--fork\fR
Show only forks

.TP
\fB\fC-q\fR, \fB\fC--jq\fR \fB\fC<expression>\fR
Filter JSON output using a jq expression

.TP
\fB\fC--json\fR \fB\fC<fields>\fR
Output JSON with the specified fields

.TP
\fB\fC-l\fR, \fB\fC--language\fR \fB\fC<string>\fR
Filter by primary coding language

.TP
\fB\fC-L\fR, \fB\fC--limit\fR \fB\fC<int>\fR
Maximum number of repositories to list

.TP
\fB\fC--no-archived\fR
Omit archived repositories

.TP
\fB\fC--source\fR
Show only non-forks

.TP
\fB\fC-t\fR, \fB\fC--template\fR \fB\fC<string>\fR
Format JSON output using a Go template

.TP
\fB\fC--topic\fR \fB\fC<string>\fR
Filter by topic

.TP
\fB\fC--visibility\fR \fB\fC<string>\fR
Filter by repository visibility: {public|private|internal}


.SH SEE ALSO
.PP
\fB\fCgh-repo(1)\fR
