.nh
.TH "GH-RELEASE" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-release - Manage releases


.SH SYNOPSIS
.PP
\fB\fCgh release <command> [flags]\fR


.SH COMMANDS
.TP
\fB\fCgh-release-create(1)\fR
Create a new release

.TP
\fB\fCgh-release-delete(1)\fR
Delete a release

.TP
\fB\fCgh-release-delete-asset(1)\fR
Delete an asset from a release

.TP
\fB\fCgh-release-download(1)\fR
Download release assets

.TP
\fB\fCgh-release-edit(1)\fR
Edit a release

.TP
\fB\fCgh-release-list(1)\fR
List releases in a repository

.TP
\fB\fCgh-release-upload(1)\fR
Upload assets to a release

.TP
\fB\fCgh-release-view(1)\fR
View information about a release


.SH OPTIONS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh(1)\fR
