.nh
.TH "GH-REPO-SYNC" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-repo-sync - Sync a repository


.SH SYNOPSIS
.PP
\fB\fCgh repo sync [<destination-repository>] [flags]\fR


.SH DESCRIPTION
.PP
Sync destination repository from source repository. Syncing uses the main branch
of the source repository to update the matching branch on the destination
repository so they are equal. A fast forward update will be used except when the
\fB\fC--force\fR flag is specified, then the two branches will
by synced using a hard reset.

.PP
Without an argument, the local repository is selected as the destination repository.

.PP
The source repository is the parent of the destination repository by default.
This can be overridden with the \fB\fC--source\fR flag.


.SH OPTIONS
.TP
\fB\fC-b\fR, \fB\fC--branch\fR \fB\fC<string>\fR
Branch to sync (default: main branch)

.TP
\fB\fC--force\fR
Hard reset the branch of the destination repository to match the source repository

.TP
\fB\fC-s\fR, \fB\fC--source\fR \fB\fC<string>\fR
Source repository


.SH EXAMPLE
.PP
.RS

.nf
# Sync local repository from remote parent
$ gh repo sync

# Sync local repository from remote parent on specific branch
$ gh repo sync --branch v1

# Sync remote fork from its parent
$ gh repo sync owner/cli-fork

# Sync remote repository from another remote repository
$ gh repo sync owner/repo --source owner2/repo2


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-repo(1)\fR
