.nh
.TH "GH-RUN-WATCH" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-run-watch - Watch a run until it completes, showing its progress


.SH SYNOPSIS
.PP
\fB\fCgh run watch <run-id> [flags]\fR


.SH OPTIONS
.TP
\fB\fC--exit-status\fR
Exit with non-zero status if run fails

.TP
\fB\fC-i\fR, \fB\fC--interval\fR \fB\fC<int>\fR
Refresh interval in seconds


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXAMPLE
.PP
.RS

.nf
# Watch a run until it's done
gh run watch

# Run some other command when the run is finished
gh run watch && notify-send "run is done!"


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-run(1)\fR
