.nh
.TH "GH-RUN-LIST" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-run-list - List recent workflow runs


.SH SYNOPSIS
.PP
\fB\fCgh run list [flags]\fR


.SH OPTIONS
.TP
\fB\fC-b\fR, \fB\fC--branch\fR \fB\fC<string>\fR
Filter runs by branch

.TP
\fB\fC-q\fR, \fB\fC--jq\fR \fB\fC<expression>\fR
Filter JSON output using a jq expression

.TP
\fB\fC--json\fR \fB\fC<fields>\fR
Output JSON with the specified fields

.TP
\fB\fC-L\fR, \fB\fC--limit\fR \fB\fC<int>\fR
Maximum number of runs to fetch

.TP
\fB\fC-t\fR, \fB\fC--template\fR \fB\fC<string>\fR
Format JSON output using a Go template

.TP
\fB\fC-u\fR, \fB\fC--user\fR \fB\fC<string>\fR
Filter runs by user who triggered the run

.TP
\fB\fC-w\fR, \fB\fC--workflow\fR \fB\fC<string>\fR
Filter runs by workflow


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-run(1)\fR
