.nh
.TH "GH-SEARCH" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-search - Search for repositories, issues, and pull requests


.SH SYNOPSIS
.PP
\fB\fCgh search <command> [flags]\fR


.SH DESCRIPTION
.PP
Search across all of GitHub.


.SH COMMANDS
.TP
\fB\fCgh-search-issues(1)\fR
Search for issues

.TP
\fB\fCgh-search-prs(1)\fR
Search for pull requests

.TP
\fB\fCgh-search-repos(1)\fR
Search for repositories


.SH SEE ALSO
.PP
\fB\fCgh(1)\fR
