.nh
.TH "GH-SSH-KEY-ADD" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-ssh-key-add - Add an SSH key to your GitHub account


.SH SYNOPSIS
.PP
\fB\fCgh ssh-key add [<key-file>] [flags]\fR


.SH OPTIONS
.TP
\fB\fC-t\fR, \fB\fC--title\fR \fB\fC<string>\fR
Title for the new key


.SH SEE ALSO
.PP
\fB\fCgh-ssh-key(1)\fR
