.nh
.TH "GH-WORKFLOW" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-workflow - View details about GitHub Actions workflows


.SH SYNOPSIS
.PP
\fB\fCgh workflow <command> [flags]\fR


.SH DESCRIPTION
.PP
List, view, and run workflows in GitHub Actions.


.SH COMMANDS
.TP
\fB\fCgh-workflow-disable(1)\fR
Disable a workflow

.TP
\fB\fCgh-workflow-enable(1)\fR
Enable a workflow

.TP
\fB\fCgh-workflow-list(1)\fR
List workflows

.TP
\fB\fCgh-workflow-run(1)\fR
Run a workflow by creating a workflow_dispatch event

.TP
\fB\fCgh-workflow-view(1)\fR
View the summary of a workflow


.SH OPTIONS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh(1)\fR
