.nh
.TH "GH-WORKFLOW-LIST" "1" "Jun 2022" "GitHub CLI 2.13.0" "GitHub CLI manual"

.SH NAME
.PP
gh-workflow-list - List workflows


.SH SYNOPSIS
.PP
\fB\fCgh workflow list [flags]\fR


.SH DESCRIPTION
.PP
List workflow files, hiding disabled workflows by default.


.SH OPTIONS
.TP
\fB\fC-a\fR, \fB\fC--all\fR
Show all workflows, including disabled workflows

.TP
\fB\fC-L\fR, \fB\fC--limit\fR \fB\fC<int>\fR
Maximum number of workflows to fetch


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-workflow(1)\fR
