subreddit: #limit to 4 b/c there are 4 cores on raspberry pi for spark to share
  - technology
  - ProgrammerHumor
  - news
  - worldnews
  - BikiniBottomTwitter
  - BlackPeopleTwitter
  - WhitePeopleTwitter
  - aws
post_type: new
bucket: reddit-streaming-stevenhurwitt-new
kafka_host: kafka
spark_host: spark-master
postgres_host: xanaxprincess.asuscomm.com
postgres_user: steven
postgres_password: Secret!1234
extra_jar_list: "org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.1,org.apache.hadoop:hadoop-common:3.3.4,org.apache.hadoop:hadoop-aws:3.3.4,org.apache.hadoop:hadoop-client:3.3.4,io.delta:delta-core_2.12:2.2.0,org.postgresql:postgresql:42.5.0"
debug: True