name: docker
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build dockerfiles
        run: ./build.sh
      - name: run docker-compose
        uses: sudo-bot/action-docker-compose@latest
        with:
            # https://docs.docker.com/compose/reference/overview/
            cli-args: "up"