name: docker
on: [push, pull_request]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "creds.json"
          json: ${{ secrets.CREDS }}
          dir: 'redditStreaming/'
      - name: create txt files
        run: touch aws_access_key.txt && touch aws_secret.txt
      - name: aws access key id
        run: 'echo "$ACCESS_KEY" > aws_access_key.txt'
        shell: bash
        env:
          ACCESS_KEY : ${{secrets.AWS_ACCESS_KEY_ID}}
      - name: aws secret key
        run: 'echo "$SECRET_KEY" > aws_secret.txt'
        shell: bash
        env:
          SECRET_KEY : ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: list directory
        run: ls
      - name: cat access_key
        run: cat aws_access_key.txt
      - name: build dockerfiles
        run: ./build.sh
      # - name: aws s3 download scripts
      #   run: aws s3 sync s3://reddit-streaming-stevenhurwitt/scripts/ redditStreaming/src/main/python/scripts/
      - name: aws s3 upload scripts
        run: aws s3 sync redditStreaming/src/main/python/scripts/ s3://reddit-streaming-stevenhurwitt/scripts/
      # - name: run docker-compose
      #   uses: sudo-bot/action-docker-compose@latest
      #   with:
      #       # https://docs.docker.com/compose/reference/overview/
      #       cli-args: "up -d"

