name: glue
on: [push]
jobs:
  glue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # - name: create-json
      #   id: create-json
      #   uses: jsdaniell/create-json@1.1.2
      #   with:
      #     name: "creds.json"
      #     json: ${{ secrets.CREDS }}
      #     dir: 'reddit-streaming/redditStreaming/'
      - name: change directory
        run: cd redditStreaming/src/main/python/glue
      - name: list directory
        run: ls
      - name: build glue
        run: python3 setup.py bdist_wheel
      - name: install glue
        run: ls dist/glue-1.0.0-py3-none-any.whl && pip3 install dist/glue-1.0.0-py3-none-any.whl --force-reinstall
      - name: run glue script
        run: ls redditStreaming/src/main/python/glue/glue && python3 -m reddit-streaming/redditStreaming/src/main/python/glue/glue
