name: glue
on: [push, pull_request]
jobs:
  glue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # - name: create-json
      #   id: create-json
      #   uses: jsdaniell/create-json@1.1.2
      #   with:
      #     name: "creds.json"
      #     json: ${{ secrets.CREDS }}
      #     dir: 'reddit-streaming/redditStreaming/'
      # - name: change directory
      #   run: cd redditStreaming/src/main/python/glue
      # - name: list directory
      #   run: ls
      - name: python dependencies
        run: sudo apt-get install python3 python3-pip python3-virtualenv python3-pytest
      - name: build glue
        run: python3 redditStreaming/src/main/python/glue/setup.py bdist_wheel
      - name: install glue
        run: pip3 install redditStreaming/src/main/python/glue/dist/glue-1.0.0-py3-none-any.whl --force-reinstall
      - name: run glue script
        run: python3 -m reddit-streaming/redditStreaming/src/main/python/glue/glue
