name: glue
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "creds.json"
          json: ${{ secrets.CREDS }}
          dir: 'redditStreaming/'
      - name: build dockerfiles
        run: ./build.sh
      - name: build glue
        run: python3 -m redditStreaming/src/main/python/glue/setup.py bdist_wheel
      - name: install glue
        run: python3 -m pip install redditStreaming/src/main/python/glue/dist/glue-1.0.0-py3-none-any.whl --force-reinstall
      # - name: run glue script
        # run: python3 -m redditStreaming/src/main/python/glue/glue
