name: pytest
on: [push, pull_request]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # - name: create-json
      #   id: create-json
      #   uses: jsdaniell/create-json@1.1.2
      #   with:
      #     name: "creds.json"
      #     json: ${{ secrets.CREDS }}
      #     dir: '/'
      - name: python dependencies
        run: sudo apt-get install python3 python3-pip python3-virtualenv python3-pytest
      - name: pip dependencies
        run: pip3 install pytest pytest-md pytest-emoji
      - name: versions
        run: python --version && pip --version
      - name: Run pytest
        uses: pavelzw/pytest-action@v1
        with:
          verbose: true
          emoji: true
          job_summary: true
          custom_arguments: '-q'
      # - name: pytest
      #   run: pytest redditStreaming/src/test/python/tests.py -v