name: pytest
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # - name: create-json
      #   id: create-json
      #   uses: jsdaniell/create-json@1.1.2
      #   with:
      #     name: "creds.json"
      #     json: ${{ secrets.CREDS }}
      #     dir: '/'
      - name: python dependencies
        run: sudo apt-get install python3 python3-pip
      - name: pip dependencies
        run: pip install pytest pytest-md pytest-emoji
      - name: source env
        run: source ~/.bashrc
      - name: versions
        run: python --version && pip --version && pytest --version
      - name: Run pytest
        uses: pavelzw/pytest-action@v1
        with:
          verbose: true
          emoji: false
          job_summary: false
          custom_arguments: 'redditStreaming/src/test/python/tests.py -q'
      # - name: pytest
      #   run: pytest redditStreaming/src/test/python/tests.py -v