name: scala
on: [push, pull_request]
jobs:
  scala:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: s4u/setup-maven-action@1.3.0
        with:
          java-version: 8
          maven-version: 3.8.2
      - uses: olafurpg/setup-scala@v11
      - name: versions
        run: mvn -version && java -version
      - name: mvn clean install
        run: cd ./redditStreaming && mvn clean package